name: Build Eleventy
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies & build
              run: |
                  npm ci
                  npm run build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3.9.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  #publish_dir is the folder on the docker instance which eleventy builds the pages to.
                  #it is not the docs folder in the repository
                  publish_dir: dist
                  #publish_branch is the branch in the repository.
                  #this is where you need to point GitHub pages
                  publish_branch: gh-pages
